# Generated by Django 3.2.20 on 2023-08-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
